//! TODO: Add more tag IDs from https://exiv2.org/tags.html
import IFDTypes from "./ifdTypes";

/**
 * Stores mappings for all default EXIF types.
 */
export const ExifTags: Record<number, { name: string; type: IFDTypes, count?: number }> = {
  0x0001: { name: "InteropIndex", type: IFDTypes.ASCII },
  0x0002: { name: "InteropVersion", type: IFDTypes.UNDEFINED },
  0x000b: { name: "ProcessingSoftware", type: IFDTypes.ASCII },
  0x00fe: { name: "SubfileType", type: IFDTypes.UINT32 },
  0x0100: { name: "ImageWidth", type: IFDTypes.UINT32 },
  0x0101: { name: "ImageLength", type: IFDTypes.UINT32 },
  0x0102: { name: "BitsPerSample", type: IFDTypes.UINT16 }, // int16u[n]!
  0x0103: { name: "Compression", type: IFDTypes.UINT16 },
  0x0106: { name: "PhotometricInterpretation", type: IFDTypes.UINT16 },
  0x0107: { name: "Thresholding", type: IFDTypes.UINT16 },
  0x0108: { name: "CellWidth", type: IFDTypes.UINT16 },
  0x0109: { name: "CellLength", type: IFDTypes.UINT16 },
  0x010a: { name: "FillOrder", type: IFDTypes.UINT16 },
  0x010d: { name: "DocumentName", type: IFDTypes.ASCII },
  0x010e: { name: "ImageDescription", type: IFDTypes.ASCII },
  0x010f: { name: "Make", type: IFDTypes.ASCII },
  0x0110: { name: "Model", type: IFDTypes.ASCII },
  
  //! 0x0111: { name: "StripOffsets", type: IFDTypes.UNDEFINED },
  //! See https://exiftool.org/TagNames/EXIF.html
  //! Ts like 7 diff tags

  0x0112: { name: "Orientation", type: IFDTypes.UINT16 },
  0x011a: { name: "XResolution", type: IFDTypes.URATIONAL64 },
  0x011b: { name: "YResolution", type: IFDTypes.URATIONAL64 },
  0x0128: { name: "ResolutionUnit", type: IFDTypes.UINT16 },
  0x0131: { name: "Software", type: IFDTypes.ASCII },
  0x0132: { name: "ModifyDate", type: IFDTypes.ASCII },
  0x013e: { name: "WhitePoint", type: IFDTypes.URATIONAL64 }, //! [n]
  0x013f: { name: "PrimaryChromatics", type: IFDTypes.URATIONAL64 }, //! [n]

  0x0211: { name: "YCbCrCoefficients", type: IFDTypes.URATIONAL64 }, //! [n]
  0x0213: { name: "YCbCrPositioning", type: IFDTypes.UINT16 }, //! [n]
  0x8769: { name: "ExifOffset", type: IFDTypes.UNDEFINED },
  0x8825: { name: "GPSInfo", type: IFDTypes.UNDEFINED },

  0x829a: { name: "ExposureTime", type: IFDTypes.URATIONAL64 },
  0x829d: { name: "FNumber", type: IFDTypes.URATIONAL64 },
  0x8822: { name: "ExposureProgram", type: IFDTypes.UINT16 },
  0x8827: { name: "ISO", type: IFDTypes.UINT16 }, //! [n]x
  0x8828: { name: "Opto-ElectricConvFactor", type: IFDTypes.UNDEFINED }, //! Type 'no'
  0x8829: { name: "Interlace", type: IFDTypes.UNDEFINED },//! Type 'no'
  0x882a: { name: "TimeZoneOffset", type: IFDTypes.INT16 },
  0x882b: { name: "SelfTimerMode", type: IFDTypes.UINT16 },
  0x8830: { name: "SensitivityType", type: IFDTypes.UINT16 },
  0x8832: { name: "RecommendedExposureIndex", type: IFDTypes.UINT32 },

  0x8833: { name: "", type: IFDTypes.UNDEFINED },
  0x8834: { name: "", type: IFDTypes.UNDEFINED },
  0x8835: { name: "", type: IFDTypes.UNDEFINED },
  0x885c: { name: "", type: IFDTypes.UNDEFINED },
  0x885d: { name: "", type: IFDTypes.UNDEFINED },
  0x885e: { name: "", type: IFDTypes.UNDEFINED },
  0x8871: { name: "", type: IFDTypes.UNDEFINED },

  0x888a: { name: "LeafSubIFD", type: IFDTypes.UNDEFINED },
  0x9000: { name: "ExifVersion", type: IFDTypes.ASCII },
  0x9003: { name: "DateTimeOriginal", type:IFDTypes.ASCII},
  0x9004: { name: "CreateDate", type: IFDTypes.ASCII },

  0x9009: { name: "", type: IFDTypes.UNDEFINED },

  0x9010: { name: "OffsetTime", type: IFDTypes.ASCII},
  0x9011: { name: "OffsetTimeOriginal", type: IFDTypes.ASCII},
  0x9012: { name: "OffsetTimeDigitizied", type: IFDTypes.ASCII},

  0x9101: { name: "", type: IFDTypes.UNDEFINED },

  0x9102: { name: "CompressedBitsPerPixel", type: IFDTypes.URATIONAL64},
  0x9201: { name: "ShutterSpeedValue", type: IFDTypes.RATIONAL64},
  0x9202: { name: "ApertureValue", type: IFDTypes.URATIONAL64},

  0x9203: { name: "", type: IFDTypes.UNDEFINED },

  0x9204: { name: "ExposureCompensation", type: IFDTypes.RATIONAL64},

  0x9205: { name: "", type: IFDTypes.UNDEFINED },
  0x9206: { name: "", type: IFDTypes.UNDEFINED },

  0x9207: { name: "MeteringMode", type: IFDTypes.UINT16},
  0x9208: { name: "LightSource", type: IFDTypes.UINT16},
  0x9209: { name: "Flash", type: IFDTypes.UINT16},
  0x920A: { name: "FocalLength", type: IFDTypes.URATIONAL64},

  0x920b: { name: "", type: IFDTypes.UNDEFINED },
  0x920c: { name: "", type: IFDTypes.UNDEFINED },
  0x920d: { name: "", type: IFDTypes.UNDEFINED },
  0x920e: { name: "", type: IFDTypes.UNDEFINED },
  0x920f: { name: "", type: IFDTypes.UNDEFINED },
  0x9210: { name: "", type: IFDTypes.UNDEFINED },
  0x9211: { name: "", type: IFDTypes.UNDEFINED },
  0x9212: { name: "", type: IFDTypes.UNDEFINED },
  0x9213: { name: "", type: IFDTypes.UNDEFINED },
  0x9214: { name: "", type: IFDTypes.UNDEFINED },
  0x9215: { name: "", type: IFDTypes.UNDEFINED },
  0x9216: { name: "", type: IFDTypes.UNDEFINED },
  0x9217: { name: "", type: IFDTypes.UNDEFINED },
  0x923a: { name: "", type: IFDTypes.UNDEFINED },
  0x923b: { name: "", type: IFDTypes.UNDEFINED },
  0x923c: { name: "", type: IFDTypes.UNDEFINED },
  0x923f: { name: "", type: IFDTypes.UNDEFINED },
  
  0x927C: { name: "MakerNote", type: IFDTypes.UNDEFINED},

  0x9286: { name: "", type: IFDTypes.UNDEFINED },
  0x9290: { name: "", type: IFDTypes.UNDEFINED },
  0x9291: { name: "", type: IFDTypes.UNDEFINED },
  0x9292: { name: "", type: IFDTypes.UNDEFINED },
  0x932f: { name: "", type: IFDTypes.UNDEFINED },
  0x9330: { name: "", type: IFDTypes.UNDEFINED },
  0x9331: { name: "", type: IFDTypes.UNDEFINED },
  0x935c: { name: "", type: IFDTypes.UNDEFINED },
  0x9400: { name: "", type: IFDTypes.UNDEFINED },
  0x9401: { name: "", type: IFDTypes.UNDEFINED },
  0x9402: { name: "", type: IFDTypes.UNDEFINED },
  0x9403: { name: "", type: IFDTypes.UNDEFINED },
  0x9404: { name: "", type: IFDTypes.UNDEFINED },
  0x9405: { name: "", type: IFDTypes.UNDEFINED },
  0x9999: { name: "", type: IFDTypes.UNDEFINED },
  0x9A00: { name: "", type: IFDTypes.UNDEFINED },
  0x9C9B: { name: "", type: IFDTypes.UNDEFINED },
  0x9C9C: { name: "", type: IFDTypes.UNDEFINED },
  0x9C9D: { name: "", type: IFDTypes.UNDEFINED },
  0x9C9F: { name: "", type: IFDTypes.UNDEFINED },
  0xa000: { name: "", type: IFDTypes.UNDEFINED },

  0xA001: { name: "ColorSpace", type: IFDTypes.UINT16},
  0xA002: { name: "ExifImageWidth", type: IFDTypes.UINT16},
  0xA003: { name: "ExifImageHeight", type: IFDTypes.UINT16},
  0xA005: { name: "InteropOffset", type: IFDTypes.UNDEFINED},
  0xA217: { name: "SensingMethod", type: IFDTypes.UINT16},
  0xA300: { name: "FileSource", type: IFDTypes.UNDEFINED},
  0xA301: { name: "SceneType", type: IFDTypes.UNDEFINED},
  0xA302: { name: "CFAPattern", type: IFDTypes.UNDEFINED},
  0xA401: { name: "CustomRendered", type: IFDTypes.UINT16},
  0xA402: { name: "ExposureMode", type: IFDTypes.UINT16},
  0xA403: { name: "WhiteBalance", type: IFDTypes.UINT16},
  0xA405: { name: "FocalLengthIn35mmFormat", type: IFDTypes.UINT16},
  0xA406: { name: "SceneCaptureType", type: IFDTypes.UINT16},
  0xA407: { name: "GainControl", type: IFDTypes.UINT16},
  0xA408: { name: "Contrast", type: IFDTypes.UINT16},
  0xA409: { name: "Saturation", type: IFDTypes.UINT16},
  0xA40A: { name: "Sharpness", type: IFDTypes.UINT16},
  0xA40C: { name: "SubjectDistanceRange", type: IFDTypes.UINT16},
  0xA420: { name: "ImageUniqueID", type: IFDTypes.ASCII},
  0xA430: { name: "OwnerName", type: IFDTypes.ASCII},
  0xA431: { name: "SerialNumber", type: IFDTypes.ASCII},
  0xA432: { name: "LensInfo", type: IFDTypes.URATIONAL64},
  0xA433: { name: "LensMake", type: IFDTypes.ASCII},
  0xA434: { name: "LensModel", type: IFDTypes.ASCII},
  0xA435: { name: "LensSerialNumber", type: IFDTypes.ASCII},

  0xA436: { name: "", type: IFDTypes.UNDEFINED },
  0xA437: { name: "", type: IFDTypes.UNDEFINED },
  0xA438: { name: "", type: IFDTypes.UNDEFINED },
  0xA439: { name: "", type: IFDTypes.UNDEFINED },
  0xA43A: { name: "", type: IFDTypes.UNDEFINED },
  0xA43B: { name: "", type: IFDTypes.UNDEFINED },
  0xA43C: { name: "", type: IFDTypes.UNDEFINED },
  0xA460: { name: "", type: IFDTypes.UNDEFINED },
  0xA461: { name: "", type: IFDTypes.UNDEFINED },
  0xA462: { name: "", type: IFDTypes.UNDEFINED },
  0xA480: { name: "", type: IFDTypes.UNDEFINED },
  0xA481: { name: "", type: IFDTypes.UNDEFINED },

  0xA500: { name: "Gamma", type: IFDTypes.URATIONAL64},
  
  0xAFC0: { name: "", type: IFDTypes.UNDEFINED },
  0xAFC1: { name: "", type: IFDTypes.UNDEFINED },
  0xAFC2: { name: "", type: IFDTypes.UNDEFINED },
  0xAFC3: { name: "", type: IFDTypes.UNDEFINED },
  0xAFC4: { name: "", type: IFDTypes.UNDEFINED },
  0xAFC5: { name: "", type: IFDTypes.UNDEFINED },
  0xB4C3: { name: "", type: IFDTypes.UNDEFINED },
  0xBC01: { name: "", type: IFDTypes.UNDEFINED },
  0xBC02: { name: "", type: IFDTypes.UNDEFINED },
  0xBC03: { name: "", type: IFDTypes.UNDEFINED },
  0xBC04: { name: "", type: IFDTypes.UNDEFINED },
  0xBC80: { name: "", type: IFDTypes.UNDEFINED },
  0xBC81: { name: "", type: IFDTypes.UNDEFINED },
  0xBC82: { name: "", type: IFDTypes.UNDEFINED },
  0xBC83: { name: "", type: IFDTypes.UNDEFINED },
  0xBCC0: { name: "", type: IFDTypes.UNDEFINED },
  0xBCC1: { name: "", type: IFDTypes.UNDEFINED },
  0xBCC2: { name: "", type: IFDTypes.UNDEFINED },
  0xBCC3: { name: "", type: IFDTypes.UNDEFINED },
  0xBCC4: { name: "", type: IFDTypes.UNDEFINED },
  0xBCC5: { name: "", type: IFDTypes.UNDEFINED },
  0xC427: { name: "", type: IFDTypes.UNDEFINED },
  0xC428: { name: "", type: IFDTypes.UNDEFINED },
  0xC429: { name: "", type: IFDTypes.UNDEFINED },
  0xC42A: { name: "", type: IFDTypes.UNDEFINED },
  0xC44F: { name: "", type: IFDTypes.UNDEFINED },
  0xC4A5: { name: "", type: IFDTypes.UNDEFINED },
  0xC519: { name: "", type: IFDTypes.UNDEFINED },
  0xC51B: { name: "", type: IFDTypes.UNDEFINED },
  0xC573: { name: "", type: IFDTypes.UNDEFINED },
  0xC580: { name: "", type: IFDTypes.UNDEFINED },
  0xC5E0: { name: "", type: IFDTypes.UNDEFINED },
  0xc612: { name: "", type: IFDTypes.UNDEFINED },
  0xc613: { name: "", type: IFDTypes.UNDEFINED },
  0xc614: { name: "", type: IFDTypes.UNDEFINED },
  0xc615: { name: "", type: IFDTypes.UNDEFINED },
  0xc616: { name: "", type: IFDTypes.UNDEFINED },
  0xc617: { name: "", type: IFDTypes.UNDEFINED },
  0xc618: { name: "", type: IFDTypes.UNDEFINED },
  0xc619: { name: "", type: IFDTypes.UNDEFINED },
  0xc61a: { name: "", type: IFDTypes.UNDEFINED },
  0xc61b: { name: "", type: IFDTypes.UNDEFINED },
  0xc61c: { name: "", type: IFDTypes.UNDEFINED },
  0xc61d: { name: "", type: IFDTypes.UNDEFINED },
  0xc61e: { name: "", type: IFDTypes.UNDEFINED },
  0xc61f: { name: "", type: IFDTypes.UNDEFINED },	
  0xc620: { name: "", type: IFDTypes.UNDEFINED },
  0xc621: { name: "", type: IFDTypes.UNDEFINED },
  0xc622: { name: "", type: IFDTypes.UNDEFINED },
  0xc623: { name: "", type: IFDTypes.UNDEFINED },
  0xc624: { name: "", type: IFDTypes.UNDEFINED },
  0xc625: { name: "", type: IFDTypes.UNDEFINED },
  0xc626: { name: "", type: IFDTypes.UNDEFINED },
  0xc627: { name: "", type: IFDTypes.UNDEFINED },
  0xc628: { name: "", type: IFDTypes.UNDEFINED },
  0xc629: { name: "", type: IFDTypes.UNDEFINED },
  0xc62a: { name: "", type: IFDTypes.UNDEFINED },
  0xc62b: { name: "", type: IFDTypes.UNDEFINED },
  0xc62c: { name: "", type: IFDTypes.UNDEFINED },
  0xc62d: { name: "", type: IFDTypes.UNDEFINED },
  0xc62e: { name: "", type: IFDTypes.UNDEFINED },
  0xc62f: { name: "", type: IFDTypes.UNDEFINED },
  0xc630: { name: "", type: IFDTypes.UNDEFINED },
  0xc631: { name: "", type: IFDTypes.UNDEFINED },
  0xc632: { name: "", type: IFDTypes.UNDEFINED },
  0xc633: { name: "", type: IFDTypes.UNDEFINED },
  0xc634: { name: "", type: IFDTypes.UNDEFINED },
  0xc635: { name: "", type: IFDTypes.UNDEFINED },
  0xc640: { name: "", type: IFDTypes.UNDEFINED },
  0xc65a: { name: "", type: IFDTypes.UNDEFINED },
  0xc65b: { name: "", type: IFDTypes.UNDEFINED },
  0xc65c: { name: "", type: IFDTypes.UNDEFINED },
  0xc65d: { name: "", type: IFDTypes.UNDEFINED },
  0xc660: { name: "", type: IFDTypes.UNDEFINED },
  0xc68b: { name: "", type: IFDTypes.UNDEFINED },
  0xc68c: { name: "", type: IFDTypes.UNDEFINED },	
  0xc68d: { name: "", type: IFDTypes.UNDEFINED },
  0xc68e: { name: "", type: IFDTypes.UNDEFINED },
  0xc68f: { name: "", type: IFDTypes.UNDEFINED },	
  0xc690: { name: "", type: IFDTypes.UNDEFINED },	
  0xc691: { name: "", type: IFDTypes.UNDEFINED },
  0xc692: { name: "", type: IFDTypes.UNDEFINED },
  0xc6bf: { name: "", type: IFDTypes.UNDEFINED },
  0xc6c5: { name: "", type: IFDTypes.UNDEFINED },
  0xc6d2: { name: "", type: IFDTypes.UNDEFINED },
  0xc6d3: { name: "", type: IFDTypes.UNDEFINED },
  0xc6f3: { name: "", type: IFDTypes.UNDEFINED },
  0xc6f4: { name: "", type: IFDTypes.UNDEFINED },
  0xc6f5: { name: "", type: IFDTypes.UNDEFINED },
  0xc6f6: { name: "", type: IFDTypes.UNDEFINED },
  0xc6f7: { name: "", type: IFDTypes.UNDEFINED },
  0xc6f8: { name: "", type: IFDTypes.UNDEFINED },
  0xc6f9: { name: "", type: IFDTypes.UNDEFINED },
  0xc6fa: { name: "", type: IFDTypes.UNDEFINED },
  0xc6fb: { name: "", type: IFDTypes.UNDEFINED },
  0xc6fc: { name: "", type: IFDTypes.UNDEFINED },
  0xc6fd: { name: "", type: IFDTypes.UNDEFINED },
  0xc6fe: { name: "", type: IFDTypes.UNDEFINED },
  0xc714: { name: "", type: IFDTypes.UNDEFINED },
  0xc715: { name: "", type: IFDTypes.UNDEFINED },
  0xc716: { name: "", type: IFDTypes.UNDEFINED },
  0xc717: { name: "", type: IFDTypes.UNDEFINED },
  0xc718: { name: "", type: IFDTypes.UNDEFINED },
  0xc719: { name: "", type: IFDTypes.UNDEFINED },
  0xc71a: { name: "", type: IFDTypes.UNDEFINED },
  0xc71b: { name: "", type: IFDTypes.UNDEFINED },
  0xc71c: { name: "", type: IFDTypes.UNDEFINED },
  0xc71d: { name: "", type: IFDTypes.UNDEFINED },
  0xc71e: { name: "", type: IFDTypes.UNDEFINED },
  0xc71f: { name: "", type: IFDTypes.UNDEFINED },
  0xc725: { name: "", type: IFDTypes.UNDEFINED },
  0xc726: { name: "", type: IFDTypes.UNDEFINED },
  0xc740: { name: "", type: IFDTypes.UNDEFINED },
  0xc741: { name: "", type: IFDTypes.UNDEFINED },
  0xc74e: { name: "", type: IFDTypes.UNDEFINED },
  0xc761: { name: "", type: IFDTypes.UNDEFINED },
  0xc763: { name: "", type: IFDTypes.UNDEFINED },
  0xc764: { name: "", type: IFDTypes.UNDEFINED },
  0xc772: { name: "", type: IFDTypes.UNDEFINED },
  0xc789: { name: "", type: IFDTypes.UNDEFINED },
  0xc791: { name: "", type: IFDTypes.UNDEFINED },
  0xc792: { name: "", type: IFDTypes.UNDEFINED },
  0xc793: { name: "", type: IFDTypes.UNDEFINED },
  0xc7a1: { name: "", type: IFDTypes.UNDEFINED },
  0xc7a3: { name: "", type: IFDTypes.UNDEFINED },
  0xc7a4: { name: "", type: IFDTypes.UNDEFINED },
  0xc7a5: { name: "", type: IFDTypes.UNDEFINED },
  0xc7a6: { name: "", type: IFDTypes.UNDEFINED },
  0xc7a7: { name: "", type: IFDTypes.UNDEFINED },
  0xc7a8: { name: "", type: IFDTypes.UNDEFINED },
  0xc7aa: { name: "", type: IFDTypes.UNDEFINED },
  0xc7b5: { name: "", type: IFDTypes.UNDEFINED },
  0xc7d5: { name: "", type: IFDTypes.UNDEFINED },
  0xc7d7: { name: "", type: IFDTypes.UNDEFINED },
  0xc7d8: { name: "", type: IFDTypes.UNDEFINED },
  0xc7e9: { name: "", type: IFDTypes.UNDEFINED },
  0xc7ea: { name: "", type: IFDTypes.UNDEFINED },
  0xc7eb: { name: "", type: IFDTypes.UNDEFINED },
  0xc7ec: { name: "", type: IFDTypes.UNDEFINED },
  0xc7ed: { name: "", type: IFDTypes.UNDEFINED },
  0xc7ee: { name: "", type: IFDTypes.UNDEFINED },
  0xcd2d: { name: "", type: IFDTypes.UNDEFINED },
  0xcd2e: { name: "", type: IFDTypes.UNDEFINED },
  0xcd30: { name: "", type: IFDTypes.UNDEFINED },
  0xcd31: { name: "", type: IFDTypes.UNDEFINED },	
  0xcd32: { name: "", type: IFDTypes.UNDEFINED },
  0xcd33: { name: "", type: IFDTypes.UNDEFINED },
  0xcd34: { name: "", type: IFDTypes.UNDEFINED },
  0xcd35: { name: "", type: IFDTypes.UNDEFINED },
  0xcd36: { name: "", type: IFDTypes.UNDEFINED },
  0xcd37: { name: "", type: IFDTypes.UNDEFINED },
  0xcd38: { name: "", type: IFDTypes.UNDEFINED },
  0xcd39: { name: "", type: IFDTypes.UNDEFINED },
  0xcd3a: { name: "", type: IFDTypes.UNDEFINED },
  0xcd3f: { name: "", type: IFDTypes.UNDEFINED },
  0xcd40: { name: "", type: IFDTypes.UNDEFINED },
  0xcd43: { name: "", type: IFDTypes.UNDEFINED },
  0xcd44: { name: "", type: IFDTypes.UNDEFINED },
  0xcd46: { name: "", type: IFDTypes.UNDEFINED },
  0xcd47: { name: "", type: IFDTypes.UNDEFINED },
  0xcd48: { name: "", type: IFDTypes.UNDEFINED },
  0xcd49: { name: "", type: IFDTypes.UNDEFINED },
  0xcd4a: { name: "", type: IFDTypes.UNDEFINED },
  0xcd4b: { name: "", type: IFDTypes.UNDEFINED },
  0xcea1: { name: "", type: IFDTypes.UNDEFINED },
  0xea1c: { name: "", type: IFDTypes.UNDEFINED },
  0xea1d: { name: "", type: IFDTypes.UNDEFINED },
  0xfde8: { name: "", type: IFDTypes.UNDEFINED },
  0xfde9: { name: "", type: IFDTypes.UNDEFINED },
  0xfdea: { name: "", type: IFDTypes.UNDEFINED },
  0xfe00: { name: "", type: IFDTypes.UNDEFINED },	
  0xfe4c: { name: "", type: IFDTypes.UNDEFINED },
  0xfe4d: { name: "", type: IFDTypes.UNDEFINED },
  0xfe4e: { name: "", type: IFDTypes.UNDEFINED },
  0xfe51: { name: "", type: IFDTypes.UNDEFINED },
  0xfe52: { name: "", type: IFDTypes.UNDEFINED },
  0xfe53: { name: "", type: IFDTypes.UNDEFINED },
  0xfe54: { name: "", type: IFDTypes.UNDEFINED },
  0xfe55: { name: "", type: IFDTypes.UNDEFINED },
  0xfe56: { name: "", type: IFDTypes.UNDEFINED },
  0xfe57: { name: "", type: IFDTypes.UNDEFINED },	
  0xfe58: { name: "", type: IFDTypes.UNDEFINED },
// END!

};

export const ExifTagsByName: Record<string, { id: number; type: IFDTypes }> = {};

for (const [idStr, tag] of Object.entries(ExifTags)) {
  const id = Number(idStr);
  ExifTagsByName[tag.name] = { id, type: tag.type };
}